name: Docker Release

on:
  push:
    tags: [ '*' ]

env:
  GHCR_REPO: ghcr.io/${{ github.repository }}

permissions:
  contents: read
  packages: write

jobs:
  changed-containers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Extract container name from tag
        id: extract_container_name
        # The tag is in the format container_name-v1.2.3
        # This step splits the tag on the last dash and outputs the container name.
        # Will error if the tag doesn't contain a dash.
        run: |
          CONTAINER_NAME=$(echo "${GITHUB_REF_NAME}" | rev | cut -d'-' -f2- | rev)
          if [[ "${CONTAINER_NAME}" == "${GITHUB_REF_NAME}" ]]; then
            echo "Error: The tag ${GITHUB_REF_NAME} doesn't contain a dash."
            exit 1
          fi
          echo "Container name: ${CONTAINER_NAME}"
          echo "container_name=${CONTAINER_NAME}" >> $GITHUB_OUTPUT
    outputs:
      container_name: ${{ steps.extract_container_name.outputs.container_name }}

  build-containers:
    needs: changed-containers
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
        runner:
          - ubuntu-latest
          - ubuntu-latest-arm-m
        exclude:
          - platform: linux/arm64
            runner: ubuntu-latest
          - platform: linux/amd64
            runner: ubuntu-latest-arm-m
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5.7.0
        with:
          images: |
            ${{ env.GHCR_REPO }}/${{ needs.changed-containers.outputs.container_name }}
            
      - name: Login to GHCR
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@14487ce63c7a62a4a324b0bfb37086795e31c6c1 # v6.16.0
        with:
          context: containers/${{ needs.changed-containers.outputs.container_name }}
          platforms: ${{ matrix.platform }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,"name=${{ env.GHCR_REPO }}/${{ needs.changed-containers.outputs.container_name }}",push-by-digest=true,name-canonical=true,push=true
          cache-from: type=gha,scope=build-${{ needs.changed-containers.outputs.container_name }}-${{ env.PLATFORM_PAIR }}
          cache-to: type=gha,scope=build-${{ needs.changed-containers.outputs.container_name }}-${{ env.PLATFORM_PAIR }},mode=max

      - name: Export digest
        run: |
          mkdir -p ${{ runner.temp }}/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "${{ runner.temp }}/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: digests-${{ env.PLATFORM_PAIR }}
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: error
          retention-days: 1

  merge:
    runs-on: ubuntu-latest
    needs:
      - changed-containers
      - build-containers
    steps:
      - name: Download digests
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-*
          merge-multiple: true

      - name: Login to GHCR
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5.7.0
        with:
          images: |
            ${{ env.GHCR_REPO }}/${{ needs.changed-containers.outputs.container_name }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=match,pattern=${{ needs.changed-containers.outputs.container_name }}-(.*),group=1
            type=sha

      - name: Create manifest list and push
        working-directory: ${{ runner.temp }}/digests
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.GHCR_REPO }}/${{ needs.changed-containers.outputs.container_name }}@sha256:%s ' *)

      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ env.GHCR_REPO }}/${{ needs.changed-containers.outputs.container_name }}:${{ steps.meta.outputs.version }}
